### ISSUE TITLE
Parsing issue in `hax_lib` attribute macro

### ISSUE THREAD

**Issue by ROMemories** [cryspen/hax#897]
I would expect the following attribute expression to be parsed successfully, since [the `as` keyword has high precedence](https://doc.rust-lang.org/reference/expressions.html#expression-precedence):

```rust
const FOO: usize = 42;

#[hax_lib::requires(x as usize < FOO)]
fn f(x: u8) {}
```

However, this results in the following compilation error:

```sh
error: expected `,`
 --> src/lib.rs:3:1
  |
3 | #[hax_lib::requires(x as usize < FOO)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Playground for reproduction:
https://hax-playground.cryspen.com/#fstar/ec8c2d81e8/gist=d2bfc88d537d49cfc1682686d423eb3f

Adding parentheses around the `as` expression allows for successful parsing:

```rust
const FOO: usize = 42;

#[hax_lib::requires((x as usize) < FOO)]
fn f(x: u8) {}
```

How are these attribute expressions handled by hax? Are they passed directly to the backend or are they somehow manipulated by the Rust compiler before that?

**Comment by W95Psp** [comment]
Thank you for your issue!

The attributes provided by hax-lib are all producing Rust code: a `requires` clause translates to a proper Rust function, and gets translated as any other piece of code. There is no custom parsing business in hax-lib; those macros accept exactly what Rust accepts, not more, not less.

I think the expression `x as usize < FOO` is not valid Rust:
```rust
const FOO: usize = 42;

fn f(x: u8) -> bool {
    x as usize < FOO
}
```

This snippet of code doesn't compile, and Rust says that `<` is not interpreted as a comparison but as a start for generic arguments (it expects `usize<..>`, where `usize` would be a type that has generics).

So I think you're just observing the same thing, in the `requires` attribute. Or maybe I am missing something?
